# Generated by Django 5.2.13 on 2026-05-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('backend', models.CharField(default='librosa', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('ok', 'ok'), ('error', 'error')], default='pending', max_length=16)),
                ('is_music', models.BooleanField(blank=True, null=True)),
                ('music_confidence', models.FloatField(blank=True, null=True)),
                ('top_label', models.CharField(blank=True, default='', max_length=128)),
                ('time_signature', models.CharField(blank=True, default='', max_length=16)),
                ('beats_per_bar', models.IntegerField(blank=True, null=True)),
                ('tempo_bpm', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['url'], name='timesig_api_url_2899fe_idx')],
            },
        ),
    ]
